name: Build and scan image

on:
  workflow_dispatch:

jobs:
  ghcr:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
      packages: write
      id-token: write
    strategy:
      matrix:
        repo:
          - "ghcr.io"
        publish:
          - true
          - false
        add-latest:
          - true
          - false
        ignore-not-fixed:
          - true
          - false
        dependency-graph:
          - true
          - false
        exclude:
          - publish: false
            add-latest: true
        include:
          - publish: true
            add-latest: false
            ignore-not-fixed: false
            dependency-graph: false
            name: "csa-demo-ghcr-push"
          - publish: true
            add-latest: true
            ignore-not-fixed: false
            dependency-graph: false
            name: "csa-demo-ghcr-push-latest"
          - publish: true
            add-latest: true
            ignore-not-fixed: true
            dependency-graph: false
            name: "csa-demo-ghcr-push-latest-ignore"
          - publish: true
            add-latest: true
            ignore-not-fixed: false
            dependency-graph: true
            name: "csa-demo-ghcr-push-latest-deps"
          - publish: true
            add-latest: true
            ignore-not-fixed: true
            dependency-graph: true
            name: "csa-demo-ghcr-push-latest-ignore-deps"
          - publish: true
            add-latest: false
            ignore-not-fixed: false
            dependency-graph: true
            name: "csa-demo-ghcr-push-deps"
          - publish: true
            add-latest: false
            ignore-not-fixed: true
            dependency-graph: true
            name: "csa-demo-ghcr-push-ignore-deps"
          - publish: true
            add-latest: false
            ignore-not-fixed: true
            dependency-graph: false
            name: "csa-demo-ghcr-push-ignore"
          - publish: false
            add-latest: false
            ignore-not-fixed: false
            dependency-graph: false
            name: "csa-demo-ghcr-no-push"
          - publish: false
            add-latest: false
            ignore-not-fixed: true
            dependency-graph: false
            name: "csa-demo-ghcr-no-push-ignore"
          - publish: false
            add-latest: false
            ignore-not-fixed: false
            dependency-graph: true
            name: "csa-demo-ghcr-no-push-deps"
          - publish: false
            add-latest: false
            ignore-not-fixed: true
            dependency-graph: true
            name: "csa-demo-ghcr-no-push-ignore-deps"
    steps:
      - uses: drewbernetes/container-security-action@v0.2.0
        with:
          image-repo: "ghcr.io"
          repo-username: ${{ github.repository_owner }}
          repo-password: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ matrix.name }}
          image-tag: "1.0"
          check-severity: CRITICAL
          grypeignore-from-s3: true
          s3-endpoint: "https://api.s3.hudson-viles.uk"
          s3-access-key: ${{secrets.S3_ACCESS_KEY}}
          s3-secret-key: ${{secrets.S3_SECRET_KEY}}
          s3-bucket: "grypeignores"
          s3-path: "container-security-action-demo.yaml"
          add-latest-tag: ${{ matrix.add-latest }}
          publish-image: ${{ matrix.publish }}
          ignore-not-fixed: ${{ matrix.ignore-not-fixed }}
          cosign-private-key: ${{secrets.COSIGN_KEY}}
          cosign-password: ${{secrets.COSIGN_PASSWORD}}
          cosign-tlog: false
          dockerfile-path: .
          enable-dependency-graph: ${{ matrix.dependency-graph }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  docker:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      matrix:
        publish:
          - true
          - false
        add-latest:
          - true
          - false
        ignore-not-fixed:
          - true
          - false
        exclude:
          - publish: false
            add-latest: true
        include:
          - publish: true
            add-latest: false
            ignore-not-fixed: false
            name: "csa-demo-docker-push"
          - publish: true
            add-latest: true
            ignore-not-fixed: false
            name: "csa-demo-docker-push-latest"
          - publish: true
            add-latest: false
            ignore-not-fixed: true
            name: "csa-demo-docker-push-ignore"
          - publish: true
            add-latest: true
            ignore-not-fixed: true
            name: "csa-demo-docker-push-latest-ignore"
          - publish: false
            add-latest: false
            ignore-not-fixed: false
            name: "csa-demo-docker-no-push"
          - publish: false
            add-latest: false
            ignore-not-fixed: true
            name: "csa-demo-docker-no-push-ignore"
    steps:
      - uses: drewbernetes/container-security-action@v0.2.0
        with:
          image-repo: "drewviles"
          repo-username: ${{ secrets.DOCKER_USER }}
          repo-password: ${{ secrets.DOCKER_PASSWORD }}
          image-name: ${{ matrix.name }}
          image-tag: "1.0"
          check-severity: CRITICAL
          grypeignore-from-s3: true
          s3-endpoint: "https://api.s3.hudson-viles.uk"
          s3-access-key: ${{secrets.S3_ACCESS_KEY}}
          s3-secret-key: ${{secrets.S3_SECRET_KEY}}
          s3-bucket: "grypeignores"
          s3-path: "container-security-action-demo.yaml"
          add-latest-tag: ${{ matrix.add-latest }}
          publish-image: ${{ matrix.publish }}
          ignore-not-fixed: ${{ matrix.ignore-not-fixed }}
          cosign-private-key: ${{secrets.COSIGN_KEY}}
          cosign-password: ${{secrets.COSIGN_PASSWORD}}
          cosign-tlog: false
          dockerfile-path: .
          github-token: ${{ secrets.GITHUB_TOKEN }}

#  external-repos:
#    runs-on: ubuntu-24.04
#    permissions:
#      contents: read
#      packages: write
#      id-token: write
#    strategy:
#      matrix:
#        publish:
#          - true
#          - false
#        add-latest:
#          - true
#          - false
#        exclude:
#          - publish: false
#            add-latest: true
#        include:
#          - publish: false
#            add-latest: false
#            name: "csa-demo-external-no-push"
#          - publish: true
#            add-latest: false
#            name: "csa-demo-external-no-latest"
#          - publish: true
#            add-latest: true
#            name: "csa-demo-external-latest"
#    steps:
#      - uses: drewbernetes/container-security-action@v0.1.0
#        with:
#          image-repo: "registry.hudson-viles.uk/public"
#          repo-username: ${{ secrets.REGISTRY_PUBLIC_USER }}
#          repo-password: ${{ secrets.REGISTRY_PUBLIC_PASSWORD }}
#          image-name: ${{ matrix.name }}
#          image-tag: "1.0"
#          check-severity: CRITICAL
#          grypeignore-from-s3: true
#          s3-endpoint: "https://api.s3.hudson-viles.uk"
#          s3-access-key: ${{secrets.S3_ACCESS_KEY}}
#          s3-secret-key: ${{secrets.S3_SECRET_KEY}}
#          s3-bucket: "grypeignores"
#          s3-path: "container-security-action-demo.yaml"
#          add-latest-tag: ${{ matrix.add-latest }}
#          publish-image: ${{ matrix.publish }}
#          cosign-private-key: ${{secrets.COSIGN_KEY}}
#          cosign-password: ${{secrets.COSIGN_PASSWORD}}
#          cosign-tlog: false
#          dockerfile-path: .
#          github-token: ${{ secrets.GITHUB_TOKEN }}
